{% set version = "0.3.0" %}

package:
  name: xpresspipe
  version: {{ version }}

source:
  url: https://github.com/XPRESSyourself/XPRESSpipe/archive/XPRESSpipe-v{{ version }}.tar.gz
  sha256:

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - julia
    - pandas
    - numpy
    - scipy
    - r-base
    - r-devtools
    - libiconv
    - ncurses
    - fastp
    - umi_tools
    - STAR
    - samtools
    - bedtools
    - htseq
    - fastqc
    - biopython
    - scikit-learn
    - matplotlib
    - seaborn
    - multiqc
    - numpydoc
    - psutil
    - pip
    - xpressplot

test:
  imports:
    - xpresspipe

about:
  home: https://github.com/XPRESSyourself/XPRESSpipe
  license: GPL-3.0
  license_file: LICENSE
  summary: 'An alignment and analysis pipeline for ribosome profiling data.'
