language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
dist: xenial
before_install:
  #Install Conda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh ;
    else
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  # Install packages
  - conda info -a
install:
  - conda env create -n test --file requirements.yml
  - source activate test
  - conda info --envs
  - conda list
  - pip install codecov
  - pip install .
  - python setup.py install
script:
  - cd tests/
  - bash test.sh  # will run all tests in the package
  - coverage run test_utils.py
  - coverage run test_arguments.py
  - bash <(curl -s https://codecov.io/bash) -cF python
  - cd ../

after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && conda build .
