# Set linux environments
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
dist: xenial
env:
  - OS="linux"

#Install Conda
before_install:
  - if [[ ("$TRAVIS_PYTHON_VERSION" == "2.7") && ("$OS" == "linux") ]]; then
        wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh ;
    elif [[ ("$TRAVIS_PYTHON_VERSION" == "2.7") && ("$OS" == "macos") ]]; then
        wget https://repo.anaconda.com/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh ;
    elif [[ ("$TRAVIS_PYTHON_VERSION" != "2.7") && ("$OS" == "linux") ]]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh ;
    elif [[ ("$TRAVIS_PYTHON_VERSION" != "2.7") && ("$OS" == "macos") ]]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh ;
    else
        echo -e "Incompatible Python version or OS option indicated\n" ;
        exit 1;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda info -a

# Install dependencies
install:
  - conda env create -v -n xpresspipe --file requirements.yml
  - source activate xpresspipe
  - conda info --envs
  - conda list
  - pip install .
  - python setup.py install

  # Install R dependencies
  - Rscript -e 'install.packages("BiocManager", repos = "http://cran.us.r-project.org")'
  - Rscript -e 'install.packages("data.table", repos = "http://cran.us.r-project.org")'
  - Rscript -e 'BiocManager::install("dupRadar", dependencies=TRUE)'
  - Rscript -e 'BiocManager::install("GenomicFeatures", dependencies=TRUE)'
  - Rscript -e 'BiocManager::install("GenomicAlignments", dependencies=TRUE)'

# Run tests
script:

  - source activate xpresspipe
  # Get references for riboseq test
  - mkdir tests/riboseq/rp_reference
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/transcripts.gtf/download -o tests/riboseq/rp_reference/transcripts.gtf
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/chr19.fa/download -o tests/riboseq/rp_reference/chr19.fa

  # Get references for paired-end test
  - mkdir tests/paired_end
  - mkdir tests/paired_end/pe_reference
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/transcripts.gtf/download -o tests/paired_end/pe_reference/transcripts.gtf
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/chr19.fa/download -o tests/paired_end/pe_reference/chr19.fa

  # Get paired-end test files
  - mkdir tests/paired_end/pe_test
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/UHR_Rep1_ERCC-Mix1_Build37-ErccTranscripts-chr22.read1.fastq/download -o tests/paired_end/pe_test/UHR_Rep1_ERCC-Mix1_Build37-ErccTranscripts-chr22.read1.fastq
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/UHR_Rep1_ERCC-Mix1_Build37-ErccTranscripts-chr22.read2.fastq/download -o tests/paired_end/pe_test/UHR_Rep1_ERCC-Mix1_Build37-ErccTranscripts-chr22.read2.fastq
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read1.fastq/download -o tests/paired_end/pe_test/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read1.fastq
  - curl -L https://sourceforge.net/projects/XPRESSpipe/files/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read2.fastq/download -o tests/paired_end/pe_test/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read2.fastq

  # Get other test files
  #- curl -L https://sourceforge.net/projects/XPRESSpipe/files/gtf_test_large.gtf/download -o tests/references/other/gtf_test_large.gtf

  # Run tests
  - coverage run tests/test_pipelines.py
  - cat tests/riboseq/riboseq_out/riboseq_test.log
  - coverage run -a tests/test_arguments.py
  - coverage run -a tests/test_utils.py
  - coverage run -a tests/test_bam.py
  - coverage run -a tests/test_modifyGTF.py
  - coverage run -a tests/test_truncateGTF.py
  - coverage run -a tests/test_analysis.py
  - coverage run -a tests/test_help.py
  - coverage report

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF python
