package:
  name: XPRESSpipe
  version: 0.0.1-beta

source:
  fn: XPRESSpipe-0.0.1b1.tar.gz
  url: https://github.com/XPRESSyourself/XPRESStools/archive/XPRESSpipe-0.0.1b1.tar.gz

test:
  commands:
    - xpresspipe --help

about:
  home: https://xpresspipe.readthedocs.io/en/latest/
  summary: An alignment and analysis pipeline for RNAseq data
  license: GPL-3.0

package:
  version: {{ environ['VERSION'] }}

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH
