name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - pandas
  - matplotlib
  - numpy
  - plotly
  - scipy
  - r
  - libiconv
  - ncurses
  - fastp
  - STAR
  - samtools
  - bedtools
  - fastqc
  - biopython
  - multiqc
  - xpressplot
  - numpydoc
  - psutil
