name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - python=3
  - pandas
  - matplotlib>=2.1.1
  - numpy>=1.9.0
  - plotly>=1.9.0
  - scipy>=0.17.0
  - r
  - libiconv
  - ncurses
  - fastp
  - STAR>=2.7
  - samtools
  - bedtools>=2.28
  - fastqc
  - biopython
  - multiqc
  - pip
  - pip:
    - xpressplot
    - numpydoc
