name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - pandas
  - numpy
  - scipy
  - r-base
  - r-devtools
  - libiconv
  - ncurses
  - fastp
  - umi_tools
  - STAR
  - samtools
  - bedtools
  - htseq
  - fastqc
  - biopython
  - matplotlib<3.0.0,>=2.1.1
  - multiqc
  - numpydoc
  - psutil
  - pip
  - pip:
    - XPRESSplot
    - scikit-learn
    - seaborn
