name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - conda-forge::python>=3.0.0
  - conda-forge::julia>=1.0.0
  - conda-forge::pandas>=1.0.0
  - conda-forge::numpy>=1.16.0
  - conda-forge::scipy
  - conda-forge::r-base>=4.0.0
  - fastp
  - umi_tools
  - STAR>=2.5.1
  - samtools
  - bedtools
  - htseq
  - codecov
  - fastqc
  - biopython
  - conda-forge::matplotlib
  - conda-forge::matplotlib-base
  - multiqc
  - numpydoc
  - psutil
  - scikit-learn
  - seaborn
  - pip:
    - typing_extensions
