name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - pandas
  - matplotlib
  - numpy
  - plotly
  - scipy
  - r
  - libiconv
  - conda-forge::ncurses
  - fastp
  - STAR
  - samtools
  - bedtools
  - htseq
  - fastqc
  - biopython
  - multiqc
  - numpydoc
  - psutil
  - pip
  - pip:
    - XPRESSplot
    - scikit-learn
    - seaborn
