name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - python>=3.0.0
  - julia
  - pandas<=0.25.3
  - numpy<=1.17.5 #float error with new version of numpy, will remove if fixed
  - scipy
  - r-base<=3.5.1
  - r-devtools
  - r-data.table
  - bioconductor-genomicfeatures
  - bioconductor-rsubread
  - bioconductor-dupradar
  - bioconductor-deseq2
  - bioconductor-apeglm
  - bioconductor-genomicalignments
  - libiconv
  - ncurses
  - fastp
  - umi_tools
  - STAR>=2.5.1
  - samtools
  - bedtools
  - htseq
  - codecov
  - fastqc
  - biopython
  - matplotlib<3.0.0,>=2.1.1
  - multiqc
  - numpydoc
  - psutil
  - scikit-learn
  - seaborn
  - xpressplot
