name: xpresspipe

channels:
  - defaults
  - r
  - bioconda
  - conda-forge

dependencies:
  - FastP
  - STAR
  - samtools
  - bedtools
  - deeptools
  - htseq
  - pandas
  - numpy
  - biopython
  - scipy
  - plotly
  - r
  - conda-forge::ncurses
  - libiconv
  - bioconductor-rsubread
  - bioconductor-dupradar
  - bioconductor-deseq2
  - matplotlib=2.2.3
  - pip
  - pip:
    - git-lfs
    - xpressplot
    - multiqc
    - numpydoc
    - PySimpleGUI
