package:
  name: xpresspipe
  version: 0.1.4b

source:
  fn: XPRESSpipe-v0.1.4b2.tar.gz
  url: https://github.com/XPRESSyourself/XPRESSpipe/archive/XPRESSpipe-v0.1.4b2.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - pandas
    - matplotlib
    - numpy
    - plotly
    - scipy
    - r
    - libiconv
    - ncurses
    - fastp
    - STAR
    - samtools
    - bedtools
    - fastqc
    - biopython
    - multiqc
    - xpressplot
    - numpydoc
    - psutil
