version: 2

# Set up variables
variables:
  setup_conda2: &setup_conda2
    run:
      shell: /bin/bash
      name: Setup python2, conda, and xpresspipe dependencies
      command: bash .circleci/build_environment.sh 2

  setup_conda3: &setup_conda3
    run:
      shell: /bin/bash
      name: Setup python3, conda, and xpresspipe dependencies
      command: bash .circleci/build_environment.sh 3

  macos: &macos
    macos:
      xcode: "9.4.1" ## Using a macOS VM image (https://circleci.com/docs/2.0/executor-types/)

  linux: &linux
    machine: true ## Using a dedicated Linux VM image (https://circleci.com/docs/2.0/executor-types/)

  install_xpresspipe: &install_xpresspipe
    run:
      name: Install xpresspipe
      command: python setup.py install

  run_tests: &run_tests
    run:
      name: Run tests
      command: |
      coverage run -m tests/test_arguments.py
      

  store_artis: &store_artis
    store_artifacts:
      path: htmlcov

# Dictate workflows
jobs:
  # Linux Builds
  test-linux-3.7:
    <<: *linux
    working_directory: ~/xpresspipe_linux_3_7
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.7
          command: |
            pyenv versions
            pyenv global 3.7.0
      - *run_tests
      - *gen_codecov
      - *store_artis

  test-linux-3.6:
    <<: *linux
    working_directory: ~/xpresspipe_linux_3_6
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.6
          command: |
            pyenv versions
            pyenv global 3.6.0
      - *run_tests
      - *gen_codecov
      - *store_artis

  test-linux-3.5:
    <<: *linux
    working_directory: ~/xpresspipe_linux_3_5
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.5
          command: |
            pyenv versions
            pyenv global 3.5.0
      - *run_tests
      - *store_artis

  test-linux-2.7:
    <<: *linux
    working_directory: ~/xpresspipe_linux_2_7
    steps:
      - checkout
      - *setup_conda2
      - *install_xpresspipe
      - run:
          name: Switch to Python v2.7
          command: |
            pyenv versions
            pyenv global 2.7.0
      - *run_tests
      - *store_artis

  # MacOS Builds
  test-macos-3.7:
    <<: *macos
    working_directory: ~/xpresspipe_macos_3_7
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.7
          command: |
            pyenv versions
            pyenv global 3.7.0
      - *run_tests
      - *store_artis

  test-macos-3.6:
    <<: *macos
    working_directory: ~/xpresspipe_macos_3_6
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.6
          command: |
            pyenv versions
            pyenv global 3.6.0
      - *run_tests
      - *store_artis

  test-macos-3.5:
    <<: *macos
    working_directory: ~/xpresspipe_macos_3_5
    steps:
      - checkout
      - *setup_conda3
      - *install_xpresspipe
      - run:
          name: Switch to Python v3.5
          command: |
            pyenv versions
            pyenv global 3.5.0
      - *run_tests
      - *store_artis

  test-macos-2.7:
    <<: *macos
    working_directory: ~/xpresspipe_macos_2_7
    steps:
      - checkout
      - *setup_conda2
      - *install_xpresspipe
      - run:
          name: Switch to Python v2.7
          command: |
            pyenv versions
            pyenv global 2.7.0
      - *run_tests
      - *store_artis

# Run workflows
workflows:
  version: 2
  test:
    jobs:
      - test-linux-3.7
      - test-linux-3.6
      - test-linux-3.5
      - test-linux-2.7
      - test-macos-3.7
      - test-macos-3.6
      - test-macos-3.5
      - test-macos-2.7
